routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\SchedualController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// These routes does not require the user to be logged in
Route::get('/', [LoginController::class, 'showLoginForm'])->name('login');
Route::get('/user/register', [RegisterController::class, 'showRegisterationForm'])->name('user.register');
Route::post('user', [TeacherController::class, 'store'])->name('user.store');

// Password Reset Routes
Route::get('password/reset/form', [ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.email.form');
Route::get('user/password/reset/{token}', [ResetPasswordController::class, 'showResetForms'])->name('password.reset.form');

/*
 * These routes require the user to be logged in
 * These routes can not be hit if the password is expired
 */
Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');

/*
 * Teacher Routes
 * All route names are prefixed with 'backend.'
 * 
 */
Route::group([
    'namespace' => 'Backend', 'as' => 'backend.',
    'middleware' => [config('access.users.teacher')]
], function () {
    
    Route::get('teacher/dashboard', [HomeController::class, 'teacherDashboard'])->name('teacher.dashboard');
    Route::post('booking/accept', [TeacherController::class, 'confirmBooking'])->name('teacher.slot.booking.confirm');
    Route::get('booking/reject/{booking}', [TeacherController::class, 'rejectBooking'])->name('teacher.slot.booking.reject');
    Route::get('teacher/bookings/requests', [TeacherController::class, 'bookingRequests'])->name('teacher.booking.requests');
    
    // Event management
    Route::post('event', [EventController::class, 'store'])->name('teacher.event.store');
    Route::get('event/create', [EventController::class, 'create'])->name('teacher.event.create');
    Route::get('teacher/event', [EventController::class, 'index'])->name('teacher.event.index');
    
    Route::group(['prefix' => 'event/{event}'], function () {
        Route::get('/', [EventController::class, 'show'])->name('teacher.event.show');
        Route::get('edit', [EventController::class, 'edit'])->name('teacher.event.edit');
        Route::patch('/', [EventController::class, 'update'])->name('teacher.event.update');
    });

    // Slot management
    Route::get('edit', [SchedualController::class, 'edit'])->name('teacher.slot.edit');
    Route::post('update', [SchedualController::class, 'update'])->name('teacher.slot.update');

    // Teacher management
    Route::group(['prefix' => 'teacher/{teacher}'], function () {
        Route::get('edit', [TeacherController::class, 'edit'])->name('teacher.edit');
        Route::patch('/', [TeacherController::class, 'update'])->name('teacher.update');
    });

    // Schedule management
    Route::group([
        'prefix' => 'teacher/schedual/',
        'namespace' => 'Teacher', 'as' => 'teacher.'
    ], function () {
        Route::get('show', [TeacherController::class, 'show'])->name('schedual.show');
        Route::post('import', [SchedualController::class, 'import'])->name('schedual.import');
        Route::get('history', [SchedualController::class, 'teacherSchedualHistroy'])->name('schedual.histroy');
        Route::post('uploaded/history', [TeacherController::class, 'uploadedSchedual'])->name('uploaded.scheduals');
    });
});

/*
 * Student Routes
 * All route names are prefixed with 'frontend.'
 * 
 */
Route::group([
    'namespace' => 'Frontend', 'as' => 'frontend.',
    'middleware' => [config('access.users.student')]
], function () {

    Route::get('student/dashboard', [HomeController::class, 'studentDashboard'])->name('student.dashboard');

    Route::group(['namespace' => 'Student', 'as' => 'student.'], function () {

        Route::get('student/event', [EventController::class, 'index'])->name('event.index');
        Route::get('student/event/show/{event}', [EventController::class, 'show'])->name('event.show');

        Route::post('teachers/search', [StudentController::class, 'searchTeachers'])->name('teachers.search');
        Route::post('book/slot', [StudentController::class, 'bookSlot'])->name('slot.book');

        Route::group(['prefix' => 'student/{student}'], function () {
            Route::get('edit', [StudentController::class, 'edit'])->name('edit');
            Route::patch('/', [StudentController::class, 'update'])->name('update');
        });

        Route::group([
            'prefix' => 'student/schedual/',
        ], function () {
            Route::get('history', [StudentController::class, 'studentSchedualHistroy'])->name('schedual.histroy');
            Route::get('request/history', [StudentController::class, 'studentRequestSchedualHistroy'])->name('request.schedual.histroy');
        });
    });
});

/*
 * Routes for both teachers and students
 */
Route::group([
    'middleware' => 'auth'
], function () {
    Route::group(['namespace' => 'Teacher', 'as' => 'teacher.'], function () {
        Route::get('teacher/schedual/slots/{teacher}', [SchedualController::class, 'teacherSchedualSlots'])->name('schedual.slots');
    });
});

app/Models/SlotBooking.php
<?php

namespace App\Models;

use App\User;

use Illuminate\Database\Eloquent\Model;

class SlotBooking extends Model
{
    protected $table = 'slot_bookings';

    const PENDING = 0;
    const ACCEPTED = 1;
    const REJECTED = 2;

    protected $fillable = [
        'id',
        'slot_id',
        'student_id',
        'teacher_id',
        'start_time',
        'end_time',
        'status',
        'created_at',
        'updated_at',
    ];

    /**
     * @return mixed
     */
    public function student()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return mixed
     */
    public function getStatusLabelAttribute() {

        if ($this->status == self::ACCEPTED)
            return '<span class="badge bg-success">Accepted</span>';
        elseif ($this->status == self::REJECTED)
            return '<span class="badge bg-danger">Rejected</span>';
        else
            return '<span class="badge bg-warning">Pending</span>';
    }

    /**
     * Get approved bookings of a teacher
     * 
     * @param Illuminate\Http\Request $request
     * 
     * @return bool
     */
    public function getApprovedBookigs() {

        return self::where('teacher_id', auth()->user()->id)
            ->where('status', self::ACCEPTED)
            ->orderBy('created_at', 'desc')
            ->get();
    }
}

app/Http/Controllers/SchedualController.php
<?php

namespace App\Http\Controllers;

use App\User;
use DateTime;
use DatePeriod;
use DateInterval;
use Carbon\Carbon;
use App\Models\Schedual;
use App\Models\SlotBooking;
use Illuminate\Http\Request;
use App\Http\Requests\Backend\User\ImportSchedualRequest;

class SchedualController extends Controller
{
    /**
     * @var $schedual
     */
    protected $schedual;

    /**
     * @var $schedual
     */
    protected $booking;

    /**
     * SchedualController cunstructor
     * 
     * @param App\Models\Schedual $schedual
     */
    public function __construct(Schedual $schedual, SlotBooking $booking) {
        $this->schedual = $schedual;
        $this->booking = $booking;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function teacherSchedualHistroy() {

        $bookings = $this->booking->getApprovedBookigs();

        return view('backend.scheduals.history')
            ->withBookings($bookings);
    }

    /**
     * edit a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit() {
        return view('backend.scheduals.edit');
    }

    /**
     * edit a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request) {

        return view('backend.scheduals.edit');
    }

    /**
     * Display teacher's schedual's slots
     *
     * @return \Illuminate\Http\Response
     */
    public function teacherSchedualSlots(User $teacher) {

        $scheduals = $this->schedual->where('teacher_id', $teacher->id)
            ->whereDate('date', Carbon::today())
            ->get();
        
        $slotsArray = [];

        foreach($scheduals as $schedual) {
            $slotsArray[] = $this->schedual->getBookedSlots($schedual);
        }

        $booked_slots   = \Arr::collapse($slotsArray);
        $all_slots      = $this->schedual->getAllSlots();
        $all_slots      = $this->schedual->convertSlotsTo12HFomat($all_slots);
        $slots          = $this->schedual->getFreeSlots($all_slots, $booked_slots);

        if (count($scheduals) > 0) {
            return view('teachers.slots')
                ->withSlots($slots)
                ->withTeacher($teacher)
                ->withDate(Carbon::today())
                ->withSchedual($this->schedual);
        }

        return view('teachers.slots')
            ->withTeacher($teacher)
            ->withDate(Carbon::today())
            ->withSchedual($this->schedual);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function import(ImportSchedualRequest $request) {

        $schedual = Schedual::importTeacherSchedual($request);

        if (!is_bool($schedual) && $schedual['errors']) {
            return redirect()->back()->withErrors($schedual['errors']);
        }            
            
        if ($schedual)
            return redirect()->back()->withFlashSuccess(__('Schedual has been imported successfully!'));
        else 
            return redirect()->back()->withFlashDanger(__('File type must be of xlsx type!'));
    }
}

resources/views/backend/scheduals/edit.blade.php
@extends('backend.layouts.app')

@section('title', 'Update Slot' .' | '. 'Scheduling')

@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-12" style="text-align:center">
                <h1 class="m-0 text-dark">Update Schedule Slots Gap</h1>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <form action="{{ route('backend.teacher.slot.update') }}" method="post">
                    @csrf
                    <div class="form-group" style="text-align:center">
                        <label>Select Slots Length</label>
                        <select name="slot-length" class="form-control">
                            <option value="00:30:00">30 Minutes</option>
                            <option value="01:00:00">60 Minutes</option>
                            <option value="01:30:00">90 Minutes</option>
                            <option value="02:00:00">120 Minutes</option>
                        </select>
                    </div>
                    <div class="offset-sm-2 col-sm-10 mt-3">
                        <button type="submit" class="btn btn-danger" style="float:right">Update</button>
                    </div>
                </form>
            </div>
            <div class="col-sm-4"></div>
        </div>
    </div>
</section>
@endsection

resources/views/backend/scheduals/history.blade.php
@extends('backend.layouts.app')

@section('title', 'Schedule History' .' | '. 'Scheduling')

@section('content')
<section class="content mt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card mt-5">
                    <div class="card-header">
                        <h1 class="m-0 text-dark" style="text-align:center">Schedule History</h1>
                    </div>
                    <div class="card-body">
                        <table id="myTable" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>{{__('Student Name')}}</th>
                                    <th>{{__('Start Date')}}</th>
                                    <th>{{__('End Date')}}</th>
                                    <th>{{__('Status')}}</th>
                                    <th>{{__('Created At')}}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($bookings as $booking)
                                    <tr>
                                        <td>{{ $booking->student->name }}</td>
                                        <td>{{ $booking->start_time }}</td>
                                        <td>{{ $booking->end_time }}</td>
                                        <td>{!! $booking->status_label !!}</td>
                                        <td>{{ $booking->created_at->toFormattedDateString() }}</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/backend/scheduals/show.blade.php
@extends('backend.layouts.app')

@section('title', 'Uploaded Schedules' .' | '. 'Schedualing')

@section('content')
<section class="content mt-5">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card mt-5">
                    <div class="card-body" style="text-align:center">
                       <h1>Uploaded Schedule Slots</h1>
                        <div class="container">
                            <form action="{{ route('backend.teacher.uploaded.scheduals') }}" method="post" id="shcedual-search">
                                @csrf
                                <div class="row">
                                    <div class="col-md-12">
                                        <label for="">Select Date:</label>
                                        <input type="text" class="date" name="date" id="datepicker" autocomplete="off">
                                    </div>
                                    <div class="col-sm-8 mt-3">
                                        <button type="submit" class="btn btn-danger" style="float:right">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div id="uploaded-schedaul_container"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection